export const m = {
  music: 'BANNER MANAGEMENT',
  registertit: 'CREATE YOUR ACCOUNT',
  indextit: 'ALBUM',
  retieve: 'RETRIEVE PASSWORD',
  reset: 'RESET PASSWORD',
  activetit: 'ACTIVE ACCOUNT',
  licencetit: 'LICENCE INQUIRY',
  acontTit: 'CREATE YOUR ACCOUNT',
  navmenu1: 'LOGIN',
  navmenu2: 'HOME',
  navmenu3: 'USER CASE',
  navmenu4: 'LICENSE INQUIRY ',
  navmenu5: 'CONTACT',
  navmenu6: 'EN/CN',
  submenu1: 'USER INFO',
  submenu2: 'CHANGE PASSWORD',
  submenu3: 'BANNER MANAGEMENT',
  submenu4: 'LOGOUT',
  seachplace: 'Please enter keyword',
  username: 'Username',
  password: 'Password',
  oldpass: 'old password',
  newpass: 'new password',
  code: 'Verification Code',
  confirmpass: 'Confirm Password',
  mail: 'Email',
  name: 'Name',
  mobile: 'Mobile',
  company: 'Company',
  address: 'Address',
  register: 'Register',
  songtitle: 'Song Title',
  productionname: 'Production Name',
  producttips: 'State the name of the production, product or brand (typically the title of a film, the name of a TV show, or the brand that is being advertised)',
  mediatype: 'Media Type',
  term: 'Term',
  termtips: 'State how long you would like to license the song for your project (e.g. 3 months, 6 months, 1 year, etc.)',
  territory: 'Territory',
  additional: 'Additional info',
  submint: 'SUBMIT',
  cancel: 'CANCEL',
  login: 'SIGN IN',
  save: 'Save',
  forgot: 'Forgot Password',
  tips: {
    t1: 'Please use letter and digit combination.',
    t2: 'The username already exists.',
    t3: 'The password consists of 6-12 characters, letters and numbers.'
  },
  search: {
    style: 'STYLE',
    library: 'LIBRARY',
    total: 'Total',
    result: 'SEARCH RESULTS',
    track: 'TRACK',
    album: 'ALBUM',
    duration: 'DURATION',
    composer: 'Composer',
    publisher: 'Publisher',
    alternate: 'Alternate'
  },
  errortips: {
    userId: '请输入用户名',
    userIdtips: '由6-12位数字和字母组成',
    userIdmore: '用户名过长',
    password: '请输入密码',
    passwordtips: '密码由6-12位数字和字母组成',
    password2: '请确认密码',
    password2tips: '两次密码输入不匹配',
    name: '请输入姓名',
    nametips: '姓名由6-12位数字和字母组成',
    namemore: '姓名过长',
    pwdconfirm: '两次密码输入不匹配',
    code: '请输入验证码',
    codetips: '请输入正确的验证码',
    mail: '请输入邮箱',
    mailtips: '请输入有效邮箱',
    mobile: '请输入手机号',
    mobiletips: '请输入有效手机号',
    mobilehas: '手机号已注册',
    comtips: '公司名称过长',
    addresstips: '地址过长',
    registerSuc: '恭喜您，成功注册，请到邮箱里去激活账号',
    registerFail: '很抱歉，系统异常，请重新注册或联系我们',
    activeSuc: 'User Active Successfully!',
    activeFail: 'User Active Fail!'
  }
}
