export const m = {
  music: 'BANNER MANAGEMENT',
  navmenu1: 'LOGIN',
  navmenu2: 'HOME',
  navmenu3: 'USER CASE',
  navmenu4: 'LICENSE INQUIRY ',
  navmenu5: 'CONTACT',
  navmenu6: 'EN/CN',
  submenu1: 'USER INFO',
  submenu2: 'CHANGE PASSWORD',
  submenu3: 'BANNER MANAGEMENT',
  submenu4: 'LOGOUT',
  seachplace: 'Please enter keyword',
  username: 'Username',
  password: 'Password',
  confirmpass: 'Confirm Password',
  mail: 'Email',
  name: 'Name',
  mobile: 'Mobile',
  company: 'Company',
  address: 'Address',
  register: 'Register',
  songtitle: 'Song Title',
  productionname: 'Production Name',
  producttips: 'State the name of the production, product or brand (typically the title of a film, the name of a TV show, or the brand that is being advertised)',
  mediatype: 'Media Type',
  term: 'Term',
  termtips: 'State how long you would like to license the song for your project (e.g. 3 months, 6 months, 1 year, etc.)',
  territory: 'Territory',
  additional: 'Additional info',
  submint: 'SUBMIT',
  cancel: 'CANCEL',
  tips: {
    t1: 'Please use letter and digit combination.',
    t2: 'The username already exists.',
    t3: 'The password consists of 6-12 characters, letters and numbers.'
  }
}
