export const m = {
  searchicon: '音乐搜索',
  infotit: '个人信息',
  music: '轮播图上传',
  registertit: '创建账号',
  indextit: '音乐专辑',
  retieve: '找回密码',
  reset: '密码重置',
  activetit: '激活账户',
  licencetit: '授权申请',
  acontTit: '账号创建',
  navmenu1: '登陆',
  navmenu2: '首页',
  navmenu3: '案例',
  navmenu4: '版权申请',
  navmenu5: '联系我们',
  navmenu6: 'EN/中文',
  submenu1: '用户信息',
  submenu2: '密码修改',
  submenu3: '轮播图管理',
  submenu4: '退出',
  seachplace: '请输入搜索内容',
  username: '用户名',
  password: '密码',
  oldpass: '旧密码',
  newpass: '新密码',
  code: '验证码',
  confirmpass: '确认密码',
  mail: '邮箱',
  name: '姓名',
  mobile: '手机号',
  company: '公司',
  address: '地址',
  register: '注册',
  songtitle: '曲目名称',
  albumname: '专辑名称',
  prodname: '作品名称',
  albumtips: '请说明所选曲目用于制作的节目，广告产品或品牌名称（通常是电影或电视节目的名称，或广告的品牌）',
  mediatype: '媒体类型',
  term: '申请授权期限',
  termtips: '请说明您希望为您的项目申请的许可时间（例如3个月，6个月，1年等）',
  territory: '授权地区',
  additional: '备注',
  submint: '提交',
  cancel: '取消',
  login: '登陆',
  save: '保存',
  forgot: '忘记密码',
  tips: {
    t1: '请用字母和数字组合。',
    t2: '用户名已存在',
    t3: '密码由6-12位数字和字母组成'
  },
  search: {
    style: '风格',
    library: '曲库',
    total: '总计',
    result: '搜索结果',
    track: '曲目',
    album: '专辑',
    duration: '时长',
    composer: '作曲家',
    publisher: '出版人',
    alternate: '代理人'
  },
  errortips: {
    userId: '请输入用户名',
    userIdtips: '用户名由3-15位数字和字母组成',
    userIdmore: '用户名过长',
    password: '请输入密码',
    passwordtips: '密码由6-12位数字和字母组成',
    password2: '请确认密码',
    password2tips: '两次密码输入不匹配',
    name: '请输入姓名',
    nametips: '姓名由6-12位数字、字母或汉字组成',
    namemore: '姓名过长',
    pwdconfirm: '两次密码输入不匹配',
    code: '请输入验证码',
    codetips: '请输入正确的验证码',
    mail: '请输入邮箱',
    mailtips: '请输入有效邮箱',
    mailexist: '邮箱已存在',
    mobile: '请输入手机号',
    mobiletips: '请输入有效手机号',
    mobilehas: '手机号已注册',
    comtips: '公司名称过长',
    addresstips: '地址过长',
    songname: '请填写歌曲名称',
    albumname: '请填写专辑名称',
    proname: '请填写作品名称',
    select: '请选择',
    term: '请填写授权期限',
    territory: '请填写授权地区',
    imgmax: '最多只可以添加8个数据',
    imgnum: '必须添加5个数据',
    imgneed: 'url地址不能为空',
    registerSuc: '恭喜您，成功注册，请到邮箱里去激活账号',
    registerFail: '很抱歉，系统异常，请重新注册或联系我们',
    activeSuc: '用户激活成功',
    activeFail: '用户激活失败',
    success: '删除成功',
    content: '请输入内容',
    errusers: '用户名或密码输入有误',
    hasregester: '用户ID、邮箱或手机号已注册。',
  },
  mediaOptions: [
    {
      value: '广告',
      label: '广告'
    },
    {
      value: '仅公司内部使用',
      label: '仅公司内部使用'
    },
    {
      value: '电影',
      label: '电影'
    },
    {
      value: '游戏',
      label: '游戏'
    },
    {
      value: '商业应用',
      label: '商业应用'
    },
    {
      value: '仅网络使用',
      label: '仅网络使用'
    },
    {
      value: '广播',
      label: '广播'
    },
  ],
  imgUrl: '请选择图片',
  videoUrl: '请输入内容',
  content: '内容'
}
