export const m = {
  music: '轮播图上传',
  navmenu1: '登陆',
  navmenu2: '首页',
  navmenu3: '案例',
  navmenu4: '版权申请',
  navmenu5: '联系我们',
  navmenu6: '英文/中文',
  submenu1: '用户信息',
  submenu2: '密码修改',
  submenu3: '轮播图管理',
  submenu4: '退出',
  seachplace: '请输入查询内容',
  username: '用户名',
  password: '密码',
  confirmpass: '确认密码',
  mail: '邮箱',
  name: '名字',
  mobile: '手机号',
  company: '公司',
  address: '地址',
  register: '注册',
  songtitle: '曲目名称',
  productionname: '专辑名称',
  producttips: '请说明所选曲目用于制作的节目，广告产品或品牌名称（通常是电影或电视节目的名称，或广告的品牌）',
  mediatype: '媒体类型',
  term: '申请授权期限',
  termtips: '请说明您希望为您的项目申请的许可时间（例如3个月，6个月，1年等）',
  territory: '授权地区',
  additional: '备注',
  submint: '提交',
  cancel: '取消',
  tips: {
    t1: 'Please use letter and digit combination.',
    t2: 'The username already exists.',
    t3: 'The password consists of 6-12 characters, letters and numbers.'
  }
}
